# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateUserWindow(object):
    def setupUi(self, CreateUserWindow):
        CreateUserWindow.setObjectName("CreateUserWindow")
        CreateUserWindow.resize(296, 315)
        self.centralwidget = QtWidgets.QWidget(CreateUserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 60, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 180, 47, 13))
        self.label_4.setObjectName("label_4")
        self.nameField = QtWidgets.QLineEdit(self.centralwidget)
        self.nameField.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.nameField.setObjectName("nameField")
        self.passwordField = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordField.setGeometry(QtCore.QRect(110, 180, 113, 20))
        self.passwordField.setObjectName("passwordField")
        self.sexCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.sexCheckBox.setGeometry(QtCore.QRect(110, 100, 70, 17))
        self.sexCheckBox.setText("")
        self.sexCheckBox.setObjectName("sexCheckBox")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(60, 240, 161, 23))
        self.saveButton.setObjectName("saveButton")
        self.rolesComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.rolesComboBox.setGeometry(QtCore.QRect(110, 130, 69, 22))
        self.rolesComboBox.setObjectName("rolesComboBox")
        CreateUserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateUserWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateUserWindow)

    def retranslateUi(self, CreateUserWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateUserWindow.setWindowTitle(_translate("CreateUserWindow", "Создание пользователя"))
        self.label.setText(_translate("CreateUserWindow", "Имя:"))
        self.label_2.setText(_translate("CreateUserWindow", "Пол:"))
        self.label_3.setText(_translate("CreateUserWindow", "Роль:"))
        self.label_4.setText(_translate("CreateUserWindow", "Пароль:"))
        self.saveButton.setText(_translate("CreateUserWindow", "Создаь пользователя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateUserWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateUserWindow()
    ui.setupUi(CreateUserWindow)
    CreateUserWindow.show()
    sys.exit(app.exec_())
